default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: "123456789"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # timeout: 5000

development:
  <<: *default
  database: FrogmiDB

test:
  <<: *default
  database: FrogmiDB

production:
  <<: *default
  database: FrogmiDB
